### GET request to example server
POST http://localhost:4000/patients/createPatient
Content-Type: application/json

{
  "patientName": "Vinnu",
  "email": "vinnu11@gmail.com",
  "dateOfBirth": "1999-06-11",
  "address": "Hyderabad"
}