### GET request to example server
POST http://localhost:4000/patients/createPatient
Content-Type: application/json

{
  "patientName": "Sarath",
  "email" : "sarath2606@gmail.com",
  "dateOfBirth": "2002-06-26",
  "address": "Hyderabad"
}